version: "3.1"

services:
  client:
    build: .
    volumes:
      - "./client:/app"
    ports:
      - "3031:3000"
    depends_on:
      - api

  api:
    build: .
    volumes:
      - "./api:/app"
    environment:
      DB_CONNECTION_STRING: postgres://test:testpass@db:5432/pern_app_db
    ports:
      - "3003:3000"
    depends_on:
      - db

  db:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: pern_app_db
      POSTGRES_USER: test
    ports:
      - "5433:5432"
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
