services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pern_app_db
    ports:
      - "5434:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pern_app_db"]
      interval: 10s
      timeout: 30s
      retries: 5

  api:
    build: .
    volumes:
      - "./api:/app"
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db/pern_app_db
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

  client:
    build: .
    volumes:
      - "./client:/app"
    ports:
      - "5173:5173"
    depends_on:
      - api
